version: '3.8'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes: 
      - ./backend:/backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend